# Generated by Django 3.1 on 2020-09-21 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookshelf', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_img', models.CharField(default='', max_length=500)),
                ('book_name', models.CharField(default='', max_length=500)),
                ('note_title', models.CharField(max_length=200)),
                ('note_contents', models.TextField()),
                ('note_date', models.DateTimeField(auto_now_add=True)),
                ('note_viewcount', models.IntegerField()),
                ('note_like', models.IntegerField(default=0)),
                ('note_private', models.BooleanField(default=True)),
                ('note_state', models.BooleanField(default=True)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookshelf.book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user')),
            ],
            options={
                'verbose_name_plural': 'notes',
                'db_table': 'note',
                'ordering': ('-note_date',),
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('like_date', models.DateTimeField(auto_now_add=True)),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.note')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user')),
            ],
            options={
                'db_table': 'note_like',
                'ordering': ('-like_date',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='', max_length=200)),
                ('comment_contents', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_state', models.BooleanField(default=True)),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.note')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user')),
            ],
            options={
                'db_table': 'note_comment',
                'ordering': ('comment_date',),
            },
        ),
    ]
