# Generated by Django 3.1 on 2020-08-25 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_idx', models.AutoField(primary_key=True, serialize=False)),
                ('comment_contents', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('note_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.note')),
            ],
            options={
                'db_table': 'note_comment',
                'ordering': ('-comment_date',),
            },
        ),
    ]
