# Generated by Django 3.1 on 2020-08-25 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_idx',
            new_name='comment_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='note_idx',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note_idx',
            new_name='note_id',
        ),
    ]
