# Generated by Django 3.1 on 2020-08-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_auto_20200825_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='note',
            new_name='note_id',
        ),
    ]
