# Generated by Django 3.1 on 2020-08-26 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_auto_20200826_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('like_user', models.CharField(max_length=200)),
                ('like_date', models.DateTimeField(auto_now_add=True)),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.note')),
            ],
            options={
                'db_table': 'note_like',
                'ordering': ('-like_date',),
            },
        ),
    ]
