# Generated by Django 3.1 on 2020-08-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='book_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='note_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='like',
            name='note_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_like',
            field=models.IntegerField(default=0),
        ),
    ]
