# Generated by Django 3.1 on 2020-08-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_auto_20200826_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_private',
            field=models.BooleanField(default=True),
        ),
    ]
