# Generated by Django 3.1 on 2020-09-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0007_auto_20200826_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like_user',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='like',
            name='like_state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='like',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='note_state',
            field=models.BooleanField(default=True),
        ),
    ]
