# Generated by Django 3.1 on 2020-08-26 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=200)),
                ('user_pw', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('user_introduction', models.TextField()),
                ('user_crea_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
                'ordering': ('-user_crea_date',),
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('shelf_id', models.AutoField(primary_key=True, serialize=False)),
                ('shelf_state', models.CharField(max_length=1)),
                ('shelf_startdate', models.CharField(max_length=200)),
                ('shelf_enddate', models.CharField(max_length=200)),
                ('shelf_star', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'user_shelf',
                'ordering': ('-shelf_id',),
            },
        ),
    ]
