# Generated by Django 3.1 on 2020-09-21 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=200)),
                ('user_pw', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('user_introduction', models.TextField()),
                ('user_crea_date', models.DateTimeField(auto_now_add=True)),
                ('user_state', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user',
                'ordering': ('-user_crea_date',),
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('follow_id', models.AutoField(primary_key=True, serialize=False)),
                ('target_user_id', models.IntegerField()),
                ('follow_dt', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'follow',
                'ordering': ('-follow_dt',),
            },
        ),
    ]
