# Generated by Django 3.1 on 2020-08-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
