# Generated by Django 3.1 on 2020-08-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200826_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='book_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
