# Generated by Django 3.1 on 2020-08-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200826_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='shelf_enddate',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='shelf_star',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='shelf_startdate',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
