# Generated by Django 3.1 on 2020-09-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200826_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_state',
            field=models.BooleanField(default=True),
        ),
    ]
